masking_strategy:
  mask_proportion: 0.15
  mask_consecutive: 1

optimizer:
  name: AdamW
  lr: 1.0e-4

scheduler:
  name: warmup_linear_decay
  warmup_step: 5000

dataloader:
  n_jobs: 4
  batch_size: 10
  
  datarc:
    file_path:
      Librispeech360: your_dataset_path # key: corresponding data path
    # you can custom your key_name and offer the corresponding path  

    target:
      - mel
      - linear

loss_function: L2

train_config:
  total_step: 50000
  log_step: 10000
  visual_step: 10000



#=============== The configuration when applying specialized feature ==================#

mel:
  win_ms: 25
  hop_ms: 10
  n_freq: 201
  n_mels: 80
  n_mfcc: 13

  input:
    feat_type: mel # feat_type can be: wav, complx, linear, mel, mfcc, phase
    channel: 0
    log: True
    delta: 0
    cmvn: True

linear:
  win_ms: 25
  hop_ms: 10
  n_freq: 201
  n_mels: 80
  n_mfcc: 13

  input:
    feat_type: linear # feat_type can be: wav, complx, linear, mel, mfcc, phase
    channel: 0
    log: True
    delta: 0
    cmvn: True