masking_strategy:
  mask_proportion: 0.15
  mask_consecutive: 1

optimizer:
  name: AdamW
  lr: 1.0e-4

scheduler:
  name: warmup_linear_decay
  warmup_step: 5000

dataloader:
  n_jobs: 4
  batch_size: 10
  
  datarc:
    Librispeech360: your_dataset_path # key: corresponding data path
    # you can custom your key_name and offer the corresponding path  
Input:
  - Mel

Target:
  - Reconstruct_Mel
  - Reconstruct_Linear

loss_function: L1

train_config:
  total_step: 50000
  log_step: 10000
  visual_step: 10000
